/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Source of truth: coen1-brain/ai/emotional_markers.js (MARKER_VALENCE + AROUSAL_MARKERS).
 * Regenerate with:  npm run markers:sync   (from the repo root)
 *
 * Guarded by coen1-brain/tests/test-marker-valence-sync.js — editing this file by hand will fail
 * that test rather than silently drift, which is the whole reason it is generated.
 *
 * 140 markers: 52 lifting, 69 weighing, 19 neither.
 */

export type MarkerValence = -1 | 0 | 1;

/** Markers that lift — valence +1. */
export const POSITIVE_EMOTIONS: readonly string[] = [
  'authentic_safety',
  'gratitude',
  'joy',
  'determination',
  'grit',
  'persistence',
  'playfulness',
  'excitement',
  'acceptance',
  'connection',
  'inspired',
  'motivation',
  'willingness',
  'empathy',
  'desire',
  'pride',
  'certainty',
  'drive',
  'courtesy',
  'consideration',
  'patience',
  'respect',
  'trust',
  'accountability',
  'confidence',
  'hope',
  'relief',
  'contentment',
  'self_compassion',
  'tenderness',
  'awe',
  'belonging',
  'agency',
  'purpose',
  'forgiveness',
  'humor',
  'generosity',
  'serenity',
  'solidarity',
  'coregulation',
  'self_regulation',
  'physical_activity',
  'energy_vitality',
  'creative_insight',
  'emotional_insight',
  'curiosity',
  'flow_state',
  'boundary_setting',
  'relationship_investment',
  'appreciation_of_others',
  'relational_openness',
  'personal_momentum',
];

/**
 * Markers that weigh — valence -1. Includes the arousal markers: being flooded weighs on you,
 * and a list shown to a reader should say so. Only the signal-curve MATH excludes them.
 */
export const NEGATIVE_EMOTIONS: readonly string[] = [
  'resentment',
  'confliction',
  'anger',
  'loneliness',
  'tiredness',
  'guilt',
  'shame',
  'frustration',
  'grief',
  'sadness',
  'overwhelm',
  'anxiety',
  'fear',
  'rage',
  'disgust',
  'contempt',
  'envy',
  'apathy',
  'resignation',
  'spite',
  'drift',
  'disengagement',
  'betrayal',
  'priority_drift',
  'relational_drift',
  'abandonment',
  'defensiveness',
  'basic_needs',
  'physical_pain',
  'physiological_trigger',
  'hunger',
  'memory_flooding',
  'regret',
  'rumination',
  'urgency',
  'confusion',
  'emotional_flooding',
  'self_judgement',
  'self_doubt',
  'cognitive_overload',
  'decision_fatigue',
  'analysis_paralysis',
  'doomscrolling',
  'interruptions',
  'boredom',
  'cognitive_dissonance',
  'denial',
  'catastrophizing',
  'rationalization',
  'self_sabotage',
  'black_and_white_thinking',
  'projection',
  'identity_crisis',
  'comparison_trap',
  'frustration_with_others',
  'responsibility_isolation',
  'external_expectations',
  'deadline_pressure',
  'financial_pressure',
  'time_blindness',
  'rejection_sensitivity',
  'task_switching_cost',
  'sensory_overload',
  'executive_function_strain',
  'working_memory_pressure',
  'emotional_dysregulation',
  'masking_fatigue',
  'body_doubling_need',
  'demand_avoidance',
];

/**
 * Markers with no inherent direction — valence 0. Observation capacity, arousal level, and
 * feelings that read either way depending on what they are about (anticipation is the standing
 * example: looking ahead is not looking forward).
 */
export const NEUTRAL_COGNITIVE_MARKERS: readonly string[] = [
  'self_awareness',
  'metacognition',
  'reason',
  'anticipation',
  'sincerity',
  'surprise',
  'vulnerability',
  'defiance',
  'vindication',
  'nostalgia',
  'dietary_impact',
  'pattern_recognition',
  'intensity',
  'mental_reframing',
  'organization',
  'risk_calibration',
  'hyperfocus_intensity',
  'hyper_empathy',
  'justice_sensitivity',
];

/**
 * A second axis over valence, not a fourth bucket — these are a SUBSET of NEGATIVE_EMOTIONS.
 * They measure activation, not direction ("overwhelmed with joy" and "overwhelmed with stress" are
 * the same marker), so the signal curves treat them as an amplifier on whichever curve is dominant
 * rather than averaging them into the negative one. Grouped displays should still show them as
 * weighing — see NEGATIVE_EMOTIONS above.
 */
export const AROUSAL_MARKERS: readonly string[] = [
  'overwhelm',
  'physiological_trigger',
  'emotional_flooding',
  'sensory_overload',
];

/**
 * Every marker the engine can score, in taxonomy order.
 *
 * This is an ALLOWLIST, and it is safe to use as one — it is generated from the taxonomy and a test
 * fails if it drifts. A stored matrix can carry keys that are no longer markers (retired ones live
 * on in rows written before they were removed), and a reader that only blocks known metadata will
 * happily render them. Filtering to this set is what makes a retirement actually disappear.
 */
export const EMOTIONAL_MATRIX_KEYS: readonly string[] = [
  'authentic_safety',
  'self_awareness',
  'metacognition',
  'gratitude',
  'joy',
  'determination',
  'grit',
  'persistence',
  'playfulness',
  'excitement',
  'acceptance',
  'connection',
  'inspired',
  'reason',
  'resentment',
  'motivation',
  'willingness',
  'empathy',
  'anticipation',
  'desire',
  'pride',
  'confliction',
  'certainty',
  'drive',
  'anger',
  'loneliness',
  'tiredness',
  'courtesy',
  'consideration',
  'patience',
  'respect',
  'trust',
  'sincerity',
  'accountability',
  'confidence',
  'guilt',
  'shame',
  'hope',
  'frustration',
  'grief',
  'sadness',
  'relief',
  'contentment',
  'self_compassion',
  'overwhelm',
  'anxiety',
  'fear',
  'rage',
  'disgust',
  'contempt',
  'envy',
  'surprise',
  'vulnerability',
  'tenderness',
  'awe',
  'belonging',
  'defiance',
  'vindication',
  'apathy',
  'resignation',
  'spite',
  'nostalgia',
  'agency',
  'purpose',
  'forgiveness',
  'humor',
  'generosity',
  'serenity',
  'drift',
  'disengagement',
  'betrayal',
  'priority_drift',
  'relational_drift',
  'abandonment',
  'defensiveness',
  'solidarity',
  'basic_needs',
  'coregulation',
  'self_regulation',
  'physical_activity',
  'dietary_impact',
  'physical_pain',
  'energy_vitality',
  'physiological_trigger',
  'hunger',
  'memory_flooding',
  'regret',
  'creative_insight',
  'pattern_recognition',
  'rumination',
  'emotional_insight',
  'intensity',
  'urgency',
  'confusion',
  'emotional_flooding',
  'self_judgement',
  'mental_reframing',
  'self_doubt',
  'cognitive_overload',
  'decision_fatigue',
  'analysis_paralysis',
  'organization',
  'doomscrolling',
  'interruptions',
  'risk_calibration',
  'curiosity',
  'flow_state',
  'boredom',
  'boundary_setting',
  'cognitive_dissonance',
  'denial',
  'catastrophizing',
  'rationalization',
  'self_sabotage',
  'black_and_white_thinking',
  'projection',
  'identity_crisis',
  'comparison_trap',
  'relationship_investment',
  'frustration_with_others',
  'appreciation_of_others',
  'relational_openness',
  'responsibility_isolation',
  'external_expectations',
  'personal_momentum',
  'deadline_pressure',
  'financial_pressure',
  'hyperfocus_intensity',
  'time_blindness',
  'rejection_sensitivity',
  'task_switching_cost',
  'sensory_overload',
  'executive_function_strain',
  'working_memory_pressure',
  'emotional_dysregulation',
  'masking_fatigue',
  'hyper_empathy',
  'body_doubling_need',
  'justice_sensitivity',
  'demand_avoidance',
];

/** Same set, for O(1) membership checks on hot read paths. */
export const CANONICAL_MARKERS: ReadonlySet<string> = new Set(EMOTIONAL_MATRIX_KEYS);

/** Every marker's valence, keyed by marker id. Complete over EMOTIONAL_MATRIX_KEYS. */
export const MARKER_VALENCE: Readonly<Record<string, MarkerValence>> = {
  authentic_safety: 1,
  self_awareness: 0,
  metacognition: 0,
  gratitude: 1,
  joy: 1,
  determination: 1,
  grit: 1,
  persistence: 1,
  playfulness: 1,
  excitement: 1,
  acceptance: 1,
  connection: 1,
  inspired: 1,
  reason: 0,
  resentment: -1,
  motivation: 1,
  willingness: 1,
  empathy: 1,
  anticipation: 0,
  desire: 1,
  pride: 1,
  confliction: -1,
  certainty: 1,
  drive: 1,
  anger: -1,
  loneliness: -1,
  tiredness: -1,
  courtesy: 1,
  consideration: 1,
  patience: 1,
  respect: 1,
  trust: 1,
  sincerity: 0,
  accountability: 1,
  confidence: 1,
  guilt: -1,
  shame: -1,
  hope: 1,
  frustration: -1,
  grief: -1,
  sadness: -1,
  relief: 1,
  contentment: 1,
  self_compassion: 1,
  overwhelm: -1,
  anxiety: -1,
  fear: -1,
  rage: -1,
  disgust: -1,
  contempt: -1,
  envy: -1,
  surprise: 0,
  vulnerability: 0,
  tenderness: 1,
  awe: 1,
  belonging: 1,
  defiance: 0,
  vindication: 0,
  apathy: -1,
  resignation: -1,
  spite: -1,
  nostalgia: 0,
  agency: 1,
  purpose: 1,
  forgiveness: 1,
  humor: 1,
  generosity: 1,
  serenity: 1,
  drift: -1,
  disengagement: -1,
  betrayal: -1,
  priority_drift: -1,
  relational_drift: -1,
  abandonment: -1,
  defensiveness: -1,
  solidarity: 1,
  basic_needs: -1,
  coregulation: 1,
  self_regulation: 1,
  physical_activity: 1,
  dietary_impact: 0,
  physical_pain: -1,
  energy_vitality: 1,
  physiological_trigger: -1,
  hunger: -1,
  memory_flooding: -1,
  regret: -1,
  creative_insight: 1,
  pattern_recognition: 0,
  rumination: -1,
  emotional_insight: 1,
  intensity: 0,
  urgency: -1,
  confusion: -1,
  emotional_flooding: -1,
  self_judgement: -1,
  mental_reframing: 0,
  self_doubt: -1,
  cognitive_overload: -1,
  decision_fatigue: -1,
  analysis_paralysis: -1,
  organization: 0,
  doomscrolling: -1,
  interruptions: -1,
  risk_calibration: 0,
  curiosity: 1,
  flow_state: 1,
  boredom: -1,
  boundary_setting: 1,
  cognitive_dissonance: -1,
  denial: -1,
  catastrophizing: -1,
  rationalization: -1,
  self_sabotage: -1,
  black_and_white_thinking: -1,
  projection: -1,
  identity_crisis: -1,
  comparison_trap: -1,
  relationship_investment: 1,
  frustration_with_others: -1,
  appreciation_of_others: 1,
  relational_openness: 1,
  responsibility_isolation: -1,
  external_expectations: -1,
  personal_momentum: 1,
  deadline_pressure: -1,
  financial_pressure: -1,
  hyperfocus_intensity: 0,
  time_blindness: -1,
  rejection_sensitivity: -1,
  task_switching_cost: -1,
  sensory_overload: -1,
  executive_function_strain: -1,
  working_memory_pressure: -1,
  emotional_dysregulation: -1,
  masking_fatigue: -1,
  hyper_empathy: 0,
  body_doubling_need: -1,
  justice_sensitivity: 0,
  demand_avoidance: -1,
};
